//This is Jenkinsfile	
echo "From Jenkinsfile"	
pipeline {	
    agent any	    
    stages {	    
        stage('build') {	        
            steps {	            
                echo "In build"
                sh "ls -l > commandResult"
                result = readFile('commandResult').trim()
                echo ${result}
            }
            }	            
        }	        
    }
